"""init schema

Revision ID: 21e6b98fdc36
Revises: 
Create Date: 2025-10-30 11:53:39.985000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e6b98fdc36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_file_create_time', 'data_file', ['create_time'], unique=False)
    op.create_index('ix_data_file_device_id', 'data_file', ['device_id'], unique=False)
    op.create_index(op.f('ix_data_file_id'), 'data_file', ['id'], unique=False)
    op.create_index('ix_data_file_task_id', 'data_file', ['task_id'], unique=False)
    op.create_index('ix_data_file_user_id', 'data_file', ['user_id'], unique=False)
    op.create_table('data_file_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_file_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_file_id', 'label_id', name='uq_data_file_label')
    )
    op.create_index(op.f('ix_data_file_label_data_file_id'), 'data_file_label', ['data_file_id'], unique=False)
    op.create_index(op.f('ix_data_file_label_id'), 'data_file_label', ['id'], unique=False)
    op.create_index('ix_data_file_label_label_id', 'data_file_label', ['label_id'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sn', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn', name='uq_device_sn')
    )
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    op.create_index(op.f('ix_device_sn'), 'device', ['sn'], unique=True)
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_label_name')
    )
    op.create_index(op.f('ix_label_id'), 'label', ['id'], unique=False)
    op.create_index(op.f('ix_label_name'), 'label', ['name'], unique=True)
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name', 'action', name='uq_operation_page_action')
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('data_file_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_log_create_time', 'operation_log', ['create_time'], unique=False)
    op.create_index(op.f('ix_operation_log_data_file_id'), 'operation_log', ['data_file_id'], unique=False)
    op.create_index(op.f('ix_operation_log_id'), 'operation_log', ['id'], unique=False)
    op.create_index('ix_operation_log_username', 'operation_log', ['username'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('user_device_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device_permission')
    )
    op.create_index('ix_user_device_permission_device_id', 'user_device_permission', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_device_permission_id'), 'user_device_permission', ['id'], unique=False)
    op.create_index(op.f('ix_user_device_permission_user_id'), 'user_device_permission', ['user_id'], unique=False)
    op.create_table('user_operation_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'operation_id', name='uq_user_operation_permission')
    )
    op.create_index(op.f('ix_user_operation_permission_id'), 'user_operation_permission', ['id'], unique=False)
    op.create_index('ix_user_operation_permission_operation_id', 'user_operation_permission', ['operation_id'], unique=False)
    op.create_index(op.f('ix_user_operation_permission_user_id'), 'user_operation_permission', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_operation_permission_user_id'), table_name='user_operation_permission')
    op.drop_index('ix_user_operation_permission_operation_id', table_name='user_operation_permission')
    op.drop_index(op.f('ix_user_operation_permission_id'), table_name='user_operation_permission')
    op.drop_table('user_operation_permission')
    op.drop_index(op.f('ix_user_device_permission_user_id'), table_name='user_device_permission')
    op.drop_index(op.f('ix_user_device_permission_id'), table_name='user_device_permission')
    op.drop_index('ix_user_device_permission_device_id', table_name='user_device_permission')
    op.drop_table('user_device_permission')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index('ix_operation_log_username', table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_data_file_id'), table_name='operation_log')
    op.drop_index('ix_operation_log_create_time', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    op.drop_index(op.f('ix_label_name'), table_name='label')
    op.drop_index(op.f('ix_label_id'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_device_sn'), table_name='device')
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.drop_table('device')
    op.drop_index('ix_data_file_label_label_id', table_name='data_file_label')
    op.drop_index(op.f('ix_data_file_label_id'), table_name='data_file_label')
    op.drop_index(op.f('ix_data_file_label_data_file_id'), table_name='data_file_label')
    op.drop_table('data_file_label')
    op.drop_index('ix_data_file_user_id', table_name='data_file')
    op.drop_index('ix_data_file_task_id', table_name='data_file')
    op.drop_index(op.f('ix_data_file_id'), table_name='data_file')
    op.drop_index('ix_data_file_device_id', table_name='data_file')
    op.drop_index('ix_data_file_create_time', table_name='data_file')
    op.drop_table('data_file')
    # ### end Alembic commands ###
