"""add_extra_field_to_users

Revision ID: 641cf7bbf59c
Revises: 4faf69075c6e
Create Date: 2025-10-24 02:26:13.362910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '641cf7bbf59c'
down_revision: Union[str, None] = '4faf69075c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'extra')
    # ### end Alembic commands ###
